name: Pre-Commit autoupdate

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  pre-commit-autoupdate:
    uses: darbiadev/.github/.github/workflows/generic-precommit-autoupdate.yaml@c4fb123ed14ed8cc9df9820ca63bace02981e9fe # v1.0.0
